server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

jwt:
  secret: F7wez7S50RGr2wIvJ03oUPDOzvxmsEQZROunPOg/Jiem3q8sOIAUtsYaM41yzcIMCxkG8yag874v3Ae1foB4/A==
  expiration: 900000
  refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG

security:
  max-failed-attempts: 5
  lock-duration-minutes: 15

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: Auth Service
    version: 1.0.0
    description: Authentication and Authorization Service