
spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://config-server:8888

jwt:
  secret: F7wez7S50RGr2wIvJ03oUPDOzvxmsEQZROunPOg/Jiem3q8sOIAUtsYaM41yzcIMCxkG8yag874v3Ae1foB4/A==


eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway

  endpoint:
    gateway:
      access: unrestricted

    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: API Gateway
    version: 1.0.0
    description: Banking API Gateway

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
