global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8888']

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']

  - job_name: 'accountnumbergen-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'beneficiary-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090']

  - job_name: 'kyc-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8086']

  - job_name: 'nominee-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087']

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8089']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'audit-log-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8091']