package com.bank.enums;

public enum AuditAction {

    REGISTERED_SUCCESS,
    REGISTERED_FAILURE,
    OTP_SUCCESS,
    OTP_FAILURE,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,

    PASSWORD_RESET,
    INVALID_PASSWORD,
    REFRESH_TOKEN_USED,

    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_BLOCKED,
    ACCOUNT_DELETED,
    ACCOUNT_VERIFIED,
    ACCOUNT_FREEZE,
    ACCOUNT_UNFREEZE,

    BENEFICIARY_ADDED,
    BENEFICIARY_APPROVED,
    BENEFICIARY_REJECTED,
    BENEFICIARY_REMOVED,

    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,

    TRANSFER_INITIATED,
    TRANSFER_SUCCESS,
    TRANSFER_FAILED,
    WITHDRAW_SUCCESS,
    DEPOSIT_SUCCESS,
    DEPOSIT_FAILED,

    CUSTOMER_UPDATED,

    ADMIN_ACTION
}
