server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations:
            classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
info:
  app:
    name: Config Server
    version: 1.0.0
    description: Centralized Configuration Server