server:
  port: 8084

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://postgres:5432/account_db
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1200000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.bank.acc.feign: DEBUG
    feign: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
info:
  app:
    name: Account Service
    version: 1.0.0
    description: Account Management Service



resilience4j:
  circuitbreaker:
    instances:
      accountnumbergen-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

      notification-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

  retry:
    instances:
      accountNumberService:
        max-attempts: 3
        wait-duration: 2s